# Generated by Django 3.1.4 on 2020-12-20 04:59

from django.db import migrations, models
import mysite.models.profile_models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=mysite.models.profile_models.upload_image_to),
        ),
    ]
